### ISSUE TITLE
show_virtual_boundary only works for rectangular boundary 

### ISSUE THREAD

**Issue by clark-mask** [elykwilliams/EvasionPaths#16]
The show_virtual_boundary function in plotting_tools.py will only accommodate a rectangular boundary since it works in terms of rectangular coordinates, while the circular boundary works in terms of polar coordinates.

**Comment by elykwilliams** [comment]
We should make sure that your results for the Collective Motion model sensors forming a circle aren't just the sensors being pushed up against the virtual boundary.

**Comment by elykwilliams** [comment]
This issue is related to #17, which should be completed first.

**Comment by elykwilliams** [comment]
Should not be added until #19 is merged for new interface
